pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "eu-west-3"
    }
    stages {
        stage("Deploy to EKS") {
            steps {
                script {
                   withCredentials([file(credentialsId: 'eks-kubeconfig', variable: 'KUBECONFIG')]) {
               sh """
               kubectl get nodes
               kubectl apply -f Kubernetes/jenkins-deploy/nginx-deployment.yaml
                """
}
                }
            }
        }
    }
}
