apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=     # "password"
  mysql-user: dXNlcg==                 # "user"
  mysql-password: dXNlcnBhc3M=         # "userpass"
